src/Plugins/Shipping.ByWeight/Areas/Admin/Controllers/ShippingByWeightController.cs
using Grand.Business.Core.Interfaces.Checkout.Shipping;
using Grand.Business.Core.Interfaces.Common.Configuration;
using Grand.Business.Core.Interfaces.Common.Directory;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Common.Stores;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Web.Common.Controllers;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Grand.Domain.Directory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shipping.ByWeight.Domain;
using Shipping.ByWeight.Models;
using Shipping.ByWeight.Services;
using Grand.Business.Core.Interfaces.Catalog.Directory;

namespace Shipping.ByWeight.Controllers
{
    [AuthorizeAdmin]
    [Area("Admin")]
    [PermissionAuthorize(PermissionSystemName.ShippingSettings)]
    public class ShippingByWeightController : BaseShippingController
    {
        private readonly IWarehouseService _warehouseService;
        private readonly IShippingMethodService _shippingMethodService;
        private readonly IStoreService _storeService;
        private readonly ICountryService _countryService;
        private readonly ByWeightShippingSettings _shippingByWeightSettings;
        private readonly IShippingByWeightService _shippingByWeightService;
        private readonly ISettingService _settingService;
        private readonly ITranslationService _translationService;
        private readonly ICurrencyService _currencyService;
        private readonly CurrencySettings _currencySettings;
        private readonly IMeasureService _measureService;
        private readonly MeasureSettings _measureSettings;

        public ShippingByWeightController(
            IWarehouseService warehouseService,
            IShippingMethodService shippingMethodService,
            IStoreService storeService,
            ICountryService countryService,
            ByWeightShippingSettings shippingByWeightSettings,
            IShippingByWeightService shippingByWeightService,
            ISettingService settingService,
            ITranslationService translationService,
            ICurrencyService currencyService,
            CurrencySettings currencySettings,
            IMeasureService measureService,
            MeasureSettings measureSettings)
        {
            _warehouseService = warehouseService;
            _shippingMethodService = shippingMethodService;
            _storeService = storeService;
            _countryService = countryService;
            _shippingByWeightSettings = shippingByWeightSettings;
            _shippingByWeightService = shippingByWeightService;
            _settingService = settingService;
            _translationService = translationService;
            _currencyService = currencyService;
            _currencySettings = currencySettings;
            _measureService = measureService;
            _measureSettings = measureSettings;
        }
        public IActionResult Configure()
        {
            var model = new ShippingByWeightListModel {
                LimitMethodsToCreated = _shippingByWeightSettings.LimitMethodsToCreated,
                DisplayOrder = _shippingByWeightSettings.DisplayOrder
            };

            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> SaveGeneralSettings(ShippingByWeightListModel model)
        {
            //save settings
            _shippingByWeightSettings.LimitMethodsToCreated = model.LimitMethodsToCreated;
            _shippingByWeightSettings.DisplayOrder = model.DisplayOrder;

            await _settingService.SaveSetting(_shippingByWeightSettings);

            return Json(new { Result = true });
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> RatesList(DataSourceRequest command)
        {
            var records = await _shippingByWeightService.GetAll(command.Page - 1, command.PageSize);

            var sbwModel = new List<ShippingByWeightModel>();
            foreach (var x in records)
            {

                var m = new ShippingByWeightModel
                {
                    Id = x.Id,
                    StoreId = x.StoreId,
                    WarehouseId = x.WarehouseId,
                    ShippingMethodId = x.ShippingMethodId,
                    CountryId = x.CountryId,
                    From = x.From,
                    To = x.To,
                    AdditionalFixedCost = x.AdditionalFixedCost,
                    PercentageRateOfSubtotal = x.PercentageRateOfSubtotal,
                    RatePerWeightUnit = x.RatePerWeightUnit,
                    LowerWeightLimit = x.LowerWeightLimit
                };
                //shipping method
                var shippingMethod = await _shippingMethodService.GetShippingMethodById(x.ShippingMethodId);
                m.ShippingMethodName = shippingMethod != null ? shippingMethod.Name : "Unavailable";
                //store
                var store = await _storeService.GetStoreById(x.StoreId);
                m.StoreName = store != null ? store.Shortcut : "*";
                //warehouse
                var warehouse = await _warehouseService.GetWarehouseById(x.WarehouseId);
                m.WarehouseName = warehouse != null ? warehouse.Name : "*";
                //country
                var c = await _countryService.GetCountryById(x.CountryId);
                m.CountryName = c != null ? c.Name : "*";
                //state
                var s = c?.StateProvinces.FirstOrDefault(y => y.Id == x.StateProvinceId);
                m.StateProvinceName = s != null ? s.Name : "*";
                //zip
                m.Zip = !string.IsNullOrEmpty(x.Zip) ? x.Zip : "*";


                var htmlSb = new StringBuilder("<div>");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.From")}: {m.From}");
                htmlSb.Append("<br />");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.To")}: {m.To}");
                htmlSb.Append("<br />");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.AdditionalFixedCost")}: {m.AdditionalFixedCost}");
                htmlSb.Append("<br />");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.RatePerWeightUnit")}: {m.RatePerWeightUnit}");
                htmlSb.Append("<br />");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.LowerWeightLimit")}: {m.LowerWeightLimit}");
                htmlSb.Append("<br />");
                htmlSb.Append($"{_translationService.GetResource("Plugins.Shipping.ByWeight.Fields.PercentageRateOfSubtotal")}: {m.PercentageRateOfSubtotal}");

                htmlSb.Append("</div>");
                m.DataHtml = htmlSb.ToString();

                sbwModel.Add(m);
            }
            var gridModel = new DataSourceResult
            {
                Data = sbwModel,
                Total = records.TotalCount
            };

            return Json(gridModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> RateDelete(string id)
        {
            var sbw = await _shippingByWeightService.GetById(id);
            if (sbw != null)
                await _shippingByWeightService.DeleteShippingByWeightRecord(sbw);

            return new JsonResult("");
        }

        public async Task<IActionResult> AddPopup()
        {
            var model = new ShippingByWeightModel {
                PrimaryStoreCurrencyCode = (await _currencyService.GetCurrencyById(_currencySettings.PrimaryStoreCurrencyId)).CurrencyCode,
                BaseWeightIn = (await _measureService.GetMeasureWeightById(_measureSettings.BaseWeightId)).Name,
                To = 1000000
            };

            var shippingMethods = await _shippingMethodService.GetAllShippingMethods();
            if (shippingMethods.Count == 0)
                return Content("No shipping methods can be loaded");

            //stores
            model.AvailableStores.Add(new SelectListItem { Text = "*", Value = " " });
            foreach (var store in await _storeService.GetAllStores())
                model.AvailableStores.Add(new SelectListItem { Text = store.Shortcut, Value = store.Id });
            //warehouses
            model.AvailableWarehouses.Add(new SelectListItem { Text = "*", Value = " " });
            foreach (var warehouses in await _warehouseService.GetAllWarehouses())
                model.AvailableWarehouses.Add(new SelectListItem { Text = warehouses.Name, Value = warehouses.Id });
            //shipping methods
            foreach (var sm in shippingMethods)
                model.AvailableShippingMethods.Add(new SelectListItem { Text = sm.Name, Value = sm.Id });
            //countries
            model.AvailableCountries.Add(new SelectListItem { Text = "*", Value = " " });
            var countries = await _countryService.GetAllCountries(showHidden: true);
            foreach (var c in countries)
                model.AvailableCountries.Add(new SelectListItem { Text = c.Name, Value = c.Id });
            //states
            model.AvailableStates.Add(new SelectListItem { Text = "*", Value = "" });

            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddPopup(ShippingByWeightModel model)
        {
            var sbw = new ShippingByWeightRecord
            {
                StoreId = model.StoreId,
                WarehouseId = model.WarehouseId,
                CountryId = model.CountryId,
                StateProvinceId = model.StateProvinceId,
                Zip = model.Zip == "*" ? null : model.Zip,

src/Plugins/Shipping.ByWeight/Areas/Admin/Views/ShippingByWeight/AddPopup.cshtml
@{
    Layout = "";
}
@model ShippingByWeightModel
@using Shipping.ByWeight.Models;
<form id="AddPopup" asp-controller="ShippingByWeight" asp-action="AddPopup" method="post"
      asp-route-ShippingByWeightId="@Context.Request.Query["ShippingByWeightId"]"
    asp-route-btnId="@Context.Request.Query["btnId"]"
    asp-route-formId="@Context.Request.Query["formId"]">
    

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-list-alt"></i>
                        @Loc["Admin.Common.AddNew"]
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
    <script>
        var mfp = $.magnificPopup.instance;
        $("#AddPopup").submit(function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr('action');
            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(),
                success: function (data) {
                    mfp.close();
                    $('#btnRefresh').click();
                }
            });
        });
    </script>
</form>

src/Plugins/Shipping.ByWeight/Areas/Admin/Views/ShippingByWeight/Configure.cshtml
@model ShippingByWeightListModel
@inject AdminAreaSettings adminAreaSettings
@using Shipping.ByWeight.Models;
@using Grand.Domain.Common;
@{
    Layout = "_ConfigurePlugin";
}
<input id="active-menu-item" type="hidden" value="/Admin/Shipping/Providers" />
<form asp-controller="ShippingByWeight" asp-action="Configure" method="post" id="shipping-byweight-form">
    
    <div class="note note-info">
        <strong>@Loc["Plugins.Shipping.ByWeight.Formula"]:</strong>
        @Loc["Plugins.Shipping.ByWeight.Formula.Value"]
    </div>

    @{
        var addNewUrl = Url.Action("AddPopup", "ShippingByWeight", new { btnId = "btnRefresh", formId = "shipping-byweight-form" });
    }

    <div class="panel panel-default">
        <div class="panel-body">
            <div id="shipping-byweight-grid"></div>
        </div>
        <div class="panel-footer">
            <a id="btnAddNewOption" href="@(addNewUrl)" class="btn default">
                @Loc["Plugins.Shipping.ByWeight.AddRecord"]
            </a>
            <input type="submit" id="btnRefresh" style="display: none" />
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#btnAddNewOption').magnificPopup({
                type: 'ajax',
                settings: { cache: false, async: false },
                midClick: true,
                callbacks: {
                    parseAjax: function (mfpResponse) {
                        mfpResponse.data = $('<div></div>').html(mfpResponse.data);
                    },
                    ajaxContentAdded: function () {
                        $('.mfp-wrap').removeAttr('tabindex');
                    }
                }
            });
            $("#shipping-byweight-grid").kendoGrid({
                dataBound: function() {
                    $('.editpopup').magnificPopup({
                        type: 'ajax',
                        settings: { cache: false, async: false },
                        callbacks: {
                            parseAjax: function (mfpResponse) {
                                mfpResponse.data = $('<div></div>').html(mfpResponse.data);
                            },
                            ajaxContentAdded: function () {
                                $('.mfp-wrap').removeAttr('tabindex');
                            }
                        }
                    });
                },
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("RatesList", "ShippingByWeight"))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        },
                        destroy: {
                            url: "@Html.Raw(Url.Action("RateDelete", "ShippingByWeight"))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                        model: {
                            id: "Id"
                        }
                    },
                    requestEnd: function (e) {
                        if (e.type == "update") {
                            this.read();
                        }
                    },
                    error: function (e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "StoreName",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.Store"]",
                    width: 300
                }, {
                    field: "WarehouseName",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.Warehouse"]",
                    width: 300
                }, {
                    field: "CountryName",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.Country"]",
                    width: 200
                }, {
                    field: "StateProvinceName",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.StateProvince"]",
                    width: 200
                }, {
                    field: "Zip",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.Zip"]",
                    width: 200
                }, {
                    field: "ShippingMethodName",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.ShippingMethod"]",
                    width: 200
                }, {
                    field: "DataHtml",
                    title: "@Loc["Plugins.Shipping.ByWeight.Fields.DataHtml"]",
                    width: 200,
                    encoded: false
                }, {
                    field: "Id",
                    title: "@Loc["Admin.Common.Edit"]",
                    width: 100,
                    template: "<a href=\"@Url.Action("EditPopup","ShippingByWeight")?id=#=Id#&btnId=btnRefresh&formId=shipping-byweight-form\" class='k-button editpopup k-button-icontext'>@Loc["Admin.Common.Edit"]</a>"
                },  {
                    command: { name: "destroy", text: "@Loc["Admin.Common.Delete"]" },
                    title: "@Loc["Admin.Common.Delete"]",
                    width: 100
                }]
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#btnRefresh').click(function () {
                //refresh grid
                var grid = $("#shipping-byweight-grid").data('kendoGrid');
                //grid.dataSource.page(1); //new search. Set page size to 1
                grid.dataSource.read();

                //return false to don't reload a page
                return false;
            });
        });
    </script>

    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-body">
                    <div class="form-group">
                        <admin-label asp-for="LimitMethodsToCreated" />
                        <div class="col-md-9 col-sm-9">
                            <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                                <admin-input asp-for="LimitMethodsToCreated" />
                                <div class="control__indicator"></div>
                            </label>
                            <span asp-validation-for="LimitMethodsToCreated"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3 col-sm-3 text-right">
                            <admin-label asp-for="DisplayOrder" class="control-label" />
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="DisplayOrder" />
                            <span asp-validation-for="DisplayOrder"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="button" id="savegeneralsettings" class="btn default" value="@Loc["Admin.Common.Save"]" />
                        <script>
                    $(function () {
                        $('#savegeneralsettings').click(function () {

                            var postData = $(this.form).serialize();
                            addAntiForgeryToken(postData);

                            $.ajax({
                                cache: false,
                                type: 'POST',
                                url: '@Url.Action("SaveGeneralSettings", "ShippingByWeight")',
                                data: postData,
                                dataType: 'json',
                                success: function (data) {
                                    alert('Saved');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert('Failed to add record.');
                                }
                            });
                            return false;
                        });
                    });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

src/Plugins/Shipping.ByWeight/Areas/Admin/Views/ShippingByWeight/EditPopup.cshtml
@{
    Layout = "";
}
@model ShippingByWeightModel
@using Shipping.ByWeight.Models;
<form id="EditPopup" asp-controller="ShippingByWeight" asp-action="EditPopup" method="post"
      asp-route-ShippingByWeightId="@Context.Request.Query["ShippingByWeightId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-list-alt"></i>
                        @Loc["Admin.Common.Edit"]
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
    <script>
        var mfp = $.magnificPopup.instance;
        $("#EditPopup").submit(function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr('action');
            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(),
                success: function (data) {
                    mfp.close();
                    $('#btnRefresh').click();
                }
            });
        });
    </script>
</form>

src/Plugins/Shipping.ByWeight/Areas/Admin/Views/ShippingByWeight/_CreateOrUpdate.cshtml
@model ShippingByWeightModel
@using Shipping.ByWeight.Models
@using Microsoft.AspNetCore.Routing
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
<script>
    $(function () {
        $("#@Html.IdFor(model => model.CountryId)").change(function () {
            var selectedItem = $(this).val();
            var ddlStates = $("#@Html.IdFor(model => model.StateProvinceId)");
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("GetStatesByCountryId", "Home", new RouteValueDictionary { { "area", "Admin" } }))",
                data: { "countryId": selectedItem, "addAsterisk": "true" },
                success: function (data) {
                    ddlStates.html('');
                    $.each(data, function (id, option) {
                        ddlStates.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve states.');
                }
            });
        });
    });
</script>

<div class="form-horizontal">
    <div class="form-body">
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="StoreId" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="StoreId" asp-items="Model.AvailableStores" />
                <span asp-validation-for="StoreId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="WarehouseId" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="WarehouseId" asp-items="Model.AvailableWarehouses" />
                <span asp-validation-for="WarehouseId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="CountryId" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="CountryId" asp-items="Model.AvailableCountries" />
                <span asp-validation-for="CountryId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="StateProvinceId" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="StateProvinceId" asp-items="Model.AvailableStates" />
                <span asp-validation-for="StateProvinceId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="Zip" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Zip" />
                <span asp-validation-for="Zip"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="ShippingMethodId" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="ShippingMethodId" asp-items="Model.AvailableShippingMethods" />
                <span asp-validation-for="ShippingMethodId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="From" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="From" /> [@Model.BaseWeightIn]
                <span asp-validation-for="From"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="To" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="To" /> [@Model.BaseWeightIn]
                <span asp-validation-for="To"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="AdditionalFixedCost" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="AdditionalFixedCost" /> [@Model.PrimaryStoreCurrencyCode]
                <span asp-validation-for="AdditionalFixedCost"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="LowerWeightLimit" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="LowerWeightLimit" />
                <span asp-validation-for="LowerWeightLimit"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="RatePerWeightUnit" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="RatePerWeightUnit" /> [@Model.PrimaryStoreCurrencyCode]
                <span asp-validation-for="RatePerWeightUnit"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 text-right">
                <admin-label asp-for="PercentageRateOfSubtotal" class="control-label" />
            </div>
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="PercentageRateOfSubtotal" />
                <span asp-validation-for="PercentageRateOfSubtotal"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="offset-sm-3 offset-md-3 col-md-9 col-sm-9">
                <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i>@Loc["Admin.Common.Save"]</button>
            </div>
        </div>
    </div>
</div>