src/Web/Grand.Web.Admin/Controllers/CourseController.cs
using Grand.Business.Core.Interfaces.Catalog.Products;
using Grand.Business.Core.Extensions;
using Grand.Business.Core.Interfaces.Common.Directory;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Common.Stores;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Business.Core.Interfaces.Marketing.Courses;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Extensions;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Grand.Domain.Courses;
using Grand.Infrastructure;
using Grand.Web.Admin.Extensions;
using Grand.Web.Admin.Interfaces;
using Grand.Web.Admin.Models.Courses;
using Microsoft.AspNetCore.Mvc;

namespace Grand.Web.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.Courses)]
    public partial class CourseController : BaseAdminController
    {

        private readonly ITranslationService _translationService;
        private readonly ICourseLevelService _courseLevelService;
        private readonly ICourseService _courseService;
        private readonly ICourseSubjectService _courseSubjectService;
        private readonly ICourseLessonService _courseLessonService;
        private readonly ICourseViewModelService _courseViewModelService;
        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly ILanguageService _languageService;
        private readonly IGroupService _groupService;

        public CourseController(ITranslationService translationService, ICourseLevelService courseLevelService, ICourseService courseService,
            ICourseSubjectService courseSubjectService, ICourseLessonService courseLessonService,
            ICourseViewModelService courseViewModelService, IWorkContext workContext, IStoreService storeService,
            ILanguageService languageService, IGroupService groupService)
        {
            _translationService = translationService;
            _courseLevelService = courseLevelService;
            _courseService = courseService;
            _courseSubjectService = courseSubjectService;
            _courseLessonService = courseLessonService;
            _courseViewModelService = courseViewModelService;
            _workContext = workContext;
            _storeService = storeService;
            _languageService = languageService;
            _groupService = groupService;
        }


        #region Level

        public IActionResult Level() => View();

        [PermissionAuthorizeAction(PermissionActionName.List)]
        [HttpPost]
        public async Task<IActionResult> Levels(DataSourceRequest command)
        {
            var levelModel = (await _courseLevelService.GetAll())
                .Select(x => x.ToModel());

            var gridModel = new DataSourceResult
            {
                Data = levelModel,
                Total = levelModel.Count()
            };
            return Json(gridModel);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost]
        public async Task<IActionResult> LevelUpdate(CourseLevelModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new DataSourceResult { Errors = ModelState.SerializeErrors() });
            }

            var level = await _courseLevelService.GetById(model.Id);
            level = model.ToEntity(level);
            await _courseLevelService.Update(level);

            return new JsonResult("");
        }

        [PermissionAuthorizeAction(PermissionActionName.Create)]
        [HttpPost]
        public async Task<IActionResult> LevelAdd(CourseLevelModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new DataSourceResult { Errors = ModelState.SerializeErrors() });
            }

            var level = new CourseLevel();
            level = model.ToEntity(level);
            await _courseLevelService.Insert(level);

            return new JsonResult("");
        }

        [PermissionAuthorizeAction(PermissionActionName.Delete)]
        [HttpPost]
        public async Task<IActionResult> LevelDelete(string id)
        {
            var level = await _courseLevelService.GetById(id);
            if (level == null)
                throw new ArgumentException("No level found with the specified id");

            await _courseLevelService.Delete(level);

            return new JsonResult("");
        }

        #endregion

        #region Course

        public IActionResult List() => View();

        [PermissionAuthorizeAction(PermissionActionName.List)]
        [HttpPost]
        public async Task<IActionResult> List(DataSourceRequest command)
        {
            var courses = await _courseService.GetAll(pageIndex: command.Page - 1, pageSize: command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = courses,
                Total = courses.TotalCount
            };
            return Json(gridModel);
        }

        [PermissionAuthorizeAction(PermissionActionName.Create)]
        public async Task<IActionResult> Create()
        {
            var model = await _courseViewModelService.PrepareCourseModel();
            //locales
            await AddLocales(_languageService, model.Locales);

            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Create(CourseModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                if (await _groupService.IsStaff(_workContext.CurrentCustomer))
                {
                    model.Stores = new string[] { _workContext.CurrentCustomer.StaffStoreId };
                }

                var course = await _courseViewModelService.InsertCourseModel(model);
                Success(_translationService.GetResource("Admin.Courses.Course.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = course.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            model = await _courseViewModelService.PrepareCourseModel(model);

            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Preview)]
        public async Task<IActionResult> Edit(string id)
        {
            var course = await _courseService.GetById(id);
            if (course == null)
                //No course found with the specified id
                return RedirectToAction("List");

            if (await _groupService.IsStaff(_workContext.CurrentCustomer))
            {
                if (!course.LimitedToStores || (course.LimitedToStores && course.Stores.Contains(_workContext.CurrentCustomer.StaffStoreId) && course.Stores.Count > 1))
                    Warning(_translationService.GetResource("Admin.Courses.Course.Permisions"));
                else
                {
                    if (!course.AccessToEntityByStore(_workContext.CurrentCustomer.StaffStoreId))
                        return RedirectToAction("List");
                }
            }

            var model = course.ToModel();
            //locales
            await AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = course.GetTranslation(x => x.Name, languageId, false);
                locale.ShortDescription = course.GetTranslation(x => x.ShortDescription, languageId, false);
                locale.Description = course.GetTranslation(x => x.Description, languageId, false);
                locale.MetaKeywords = course.GetTranslation(x => x.MetaKeywords, languageId, false);
                locale.MetaDescription = course.GetTranslation(x => x.MetaDescription, languageId, false);
                locale.MetaTitle = course.GetTranslation(x => x.MetaTitle, languageId, false);
                locale.SeName = course.GetSeName(languageId, false);
            });

            model = await _courseViewModelService.PrepareCourseModel(model);

            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Edit(CourseModel model, bool continueEditing)
        {
            var course = await _courseService.GetById(model.Id);
            if (course == null)
                //No course found with the specified id
                return RedirectToAction("List");

            if (await _groupService.IsStaff(_workContext.CurrentCustomer))
            {
                if (!course.AccessToEntityByStore(_workContext.CurrentCustomer.StaffStoreId))
                    return RedirectToAction("Edit", new { id = course.Id });
            }

            if (ModelState.IsValid)
            {
                if (await _groupService.IsStaff(_workContext.CurrentCustomer))
                {
                    model.Stores = new string[] { _workContext.CurrentCustomer.StaffStoreId };
                }

                course = await _courseViewModelService.UpdateCourseModel(course, model);

                Success(_translationService.GetResource("Admin.Courses.Course.Updated"));
                if (continueEditing)
                {
                    //selected tab
                    await SaveSelectedTabIndex();

                    return RedirectToAction("Edit", new { id = course.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            model = await _courseViewModelService.PrepareCourseModel(model);
            
            return View(model);
        }

src/Web/Grand.Web.Admin/Areas/Admin/Views/Course/Partials/CreateOrUpdate.Lesson.cshtml
@model CourseModel
<vc:admin-widget widget-zone="course_details_lesson_top" additional-data="Model" />
@if (!String.IsNullOrEmpty(Model.Id))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            @Loc["Admin.Courses.Course.Lessons"]
        </div>
        <div class="panel-body">
            <div id="lessons-grid"></div>
        </div>
        <div class="panel-footer">
            <button type="submit" id="btnAddNewLesson" name="btnAddNewLesson" onclick="javascript:setLocation('@(Url.Action("CreateLesson", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))'); return false;" class="k-button"><i class="fa fa-plus"></i>&nbsp;@Loc["Admin.Courses.Course.Lesson.AddNew"]</button>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $("#lessons-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("Lessons", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        },
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                        model: {
                            id: "Id",
                            fields: {
                                Name: { editable: false, type: "string" },
                                DisplayOrder: {editable: false, type: "number" },
                            }
                        }
                    },
                    requestEnd: function(e) {
                        if(e.type=="update") {
                            this.read();
                        }
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "Name",
                    title: "@Loc["Admin.Courses.Course.Lesson.Fields.Name"]",
                    template: '<a class="k-link" href="@Url.Action("EditLesson", "Course", new { area = Constants.AreaAdmin })/#=Id#">#=kendo.htmlEncode(Name)#</a>',
                }, {
                    field: "DisplayOrder",
                    title: "@Loc["Admin.Courses.Course.Lesson.Fields.DisplayOrder"]",
                    //integer format
                    format: "{0:0}",
                    width: 80,
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                }]
            });
        });
    </script>
}
else
{
    <div class="note note-info">
        @Loc["Admin.Courses.Course.Lesson.SaveBeforeEdit"]
    </div>
}
<vc:admin-widget widget-zone="course_details_lesson_bottom" additional-data="Model" />

src/Web/Grand.Web.Admin/Areas/Admin/Views/Course/Partials/CreateOrUpdate.Subject.cshtml
@model CourseModel
<vc:admin-widget widget-zone="course_details_subject_top" additional-data="Model" />
@if (!String.IsNullOrEmpty(Model.Id))
{
    <div class="panel panel-default">
        <div class="panel-body">
            <div id="subjects-grid"></div>
        </div>
    </div>

    <script>
    $(document).ready(function() {
        $("#subjects-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("Subjects", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                    create: {
                        url: "@Html.Raw(Url.Action("SubjectAdd", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                    update: {
                        url: "@Html.Raw(Url.Action("SubjectUpdate", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("SubjectDelete", "Course", new { courseId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            Name: { editable: true, type: "string" },
                            DisplayOrder: { editable: true, type: "number" },
                            Id: { editable: false, type: "string" }
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "create" || e.type == "update") {
                        this.read();
                    }
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            toolbar: [{ name: "create", text: "@Loc["Admin.Common.AddNewRecord"]" }],
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: false,
            columns: [
            {
                field: "Name",
                title: "@Loc["Admin.Courses.Course.Subject.Fields.Name"]",
                width: 400
            }, {
                field: "DisplayOrder",
                title: "@Loc["Admin.Courses.Course.Subject.Fields.DisplayOrder"]",
                //integer format
                format: "{0:0}",
                width: 100
            }, {
                command: [
                {
                    name: "edit",
                    text: {
                        edit: "@Loc["Admin.Common.Edit"]",
                        update: "@Loc["Admin.Common.Update"]",
                        cancel: "@Loc["Admin.Common.Cancel"]"
                    }
                }, {
                    name: "destroy",
                    text: "@Loc["Admin.Common.Delete"]"
                        }
                    ],
                    width: 200
                }
            ]
        });
    });
    </script>
}
else
{
    <div class="note note-info">
        @Loc["Admin.Courses.Course.Subject.SaveBeforeEdit"]
    </div>
}
<vc:admin-widget widget-zone="course_details_subject_bottom" additional-data="Model" />

src/Web/Grand.Web.Admin/Areas/Admin/Views/Course/Partials/CreateOrUpdate.TabInfo.cshtml
@model CourseModel
@using Microsoft.AspNetCore.Mvc.Razor;

<script>
    $(document).ready(function () {
        toggleRemoveButton();
    });
    function toggleRemoveButton() {
        if ($('#@Html.IdFor(model => model.ProductId)').val() != '' ) {
            $('#purchased-with-product-name-remove').show();
        }
        else {
            $('#purchased-with-product-name-remove').hide();
        }
    }
</script>
<vc:admin-widget widget-zone="course_details_info_top" additional-data="Model" />

@{ Func<int, HelperResult>
         template = @<div class="form-body">
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].Name" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="@Model.Locales[item].Name" />
                    <span asp-validation-for="@Model.Locales[item].Name"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].ShortDescription" />
                <div class="col-md-9 col-sm-9">
                    <admin-textarea asp-for="@Model.Locales[item].ShortDescription"></admin-textarea>
                    <span asp-validation-for="@Model.Locales[item].ShortDescription"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].Description" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="@Model.Locales[item].Description" asp-template="Editor" />
                    <span asp-validation-for="@Model.Locales[item].Description"></span>
                </div>
            </div>
            <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
        </div>;
}

<div class="form-horizontal">
    <localized-editor localized-template=@template name="course-info-localized" language-ids=@Model.Locales.Select(c=>c.LanguageId).ToList()>
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="Name" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="ShortDescription" />
                <div class="col-md-9 col-sm-9">
                    <admin-textarea asp-for="ShortDescription"></admin-textarea>
                    <span asp-validation-for="ShortDescription"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="Description" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="Description" asp-template="Editor" />
                    <span asp-validation-for="Description"></span>
                </div>
            </div>
        </div>
    </localized-editor>
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="PictureId" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="PictureId" />
                <span asp-validation-for="PictureId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="LevelId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="LevelId" asp-items="Model.AvailableLevels" />
                <span asp-validation-for="LevelId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Published" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="Published" />
                    <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="Published"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DisplayOrder" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="DisplayOrder" />
                <span asp-validation-for="DisplayOrder"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Stores" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Stores" />
                <span asp-validation-for="Stores"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="ProductId" />
            <div class="col-md-9 col-sm-9">
                <input asp-for="ProductId" type="hidden" />
                <label class="control-label" id="purchased-with-product-name">
                    @if (!string.IsNullOrEmpty(Model.ProductId) && !string.IsNullOrEmpty(Model.ProductName))
                    {
                        @Html.ActionLink(Model.ProductName, "Edit", "Product", new { id = Model.ProductId })
                    }
                </label>
                <span asp-validation-for="ProductId"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3"></div>
            <div class="col-md-9 col-sm-9">
                <a id="btnAssociateProductToCoursePopup" href="@(Url.Action("AssociateProductToCoursePopup", "Course",
                                new { productIdInput = Html.IdFor(model => model.ProductId),
                                    productNameInput = "purchased-with-product-name",
                                    btnId = "btnRefreshPurchasedWithProduct", area = Constants.AreaAdmin }))" class="k-button">
                    @Loc["Admin.Courses.Course.Fields.PurchasedWithProduct.Choose"]
                </a>
                <button type="button" id="purchased-with-product-name-remove" class="k-button">
                    @Loc["Admin.Courses.Course.Fields.PurchasedWithProduct.Remove"]
                </button>
                <input type="button" id="btnRefreshPurchasedWithProduct" style="display: none" />
                <script>
                            $(document).ready(function () {
                                $('#btnAssociateProductToCoursePopup').magnificPopup({
                                    type: 'ajax',
                                    settings: { cache: false, async: false },
                                    midClick: true,
                                    callbacks: {
                                        parseAjax: function (mfpResponse) {
                                            mfpResponse.data = $('<div></div>').html(mfpResponse.data);
                                        },
                                        ajaxContentAdded: function () {
                                            $('.mfp-wrap').removeAttr('tabindex');
                                        }
                                    }
                                });
                                $('#purchased-with-product-name-remove').click(function () {
                                    $('#purchased-with-product-name').text('');
                                    $("#@Html.IdFor(model => model.ProductId)").val('');
                                    toggleRemoveButton();
                                    //return false to don't reload a page
                                    return false;
                                });
                                $('#btnRefreshPurchasedWithProduct').click(function () {
                                    toggleRemoveButton();
                                    //return false to don't reload a page
                                    return false;
                                });
                            });
                </script>
            </div>
        </div>
    </div>
</div>

<vc:admin-widget widget-zone="course_details_info_bottom" additional-data="Model" />

src/Web/Grand.Web.Admin/Areas/Admin/Views/Course/Partials/CreateOrUpdate.TabSeo.cshtml
@model CourseModel
@using Microsoft.AspNetCore.Mvc.Razor;

<vc:admin-widget widget-zone="course_details_seo_top" additional-data="Model" />

@{ Func<int, HelperResult>
         template = @<div class="form-body">
        <div class="form-group">
            <admin-label asp-for="@Model.Locales[item].MetaKeywords" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="@Model.Locales[item].MetaKeywords" />
                <span asp-validation-for="@Model.Locales[item].MetaKeywords"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="@Model.Locales[item].MetaDescription" />
            <div class="col-md-9 col-sm-9">
                <admin-textarea asp-for="@Model.Locales[item].MetaDescription"></admin-textarea>
                <span asp-validation-for="@Model.Locales[item].MetaDescription"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="@Model.Locales[item].MetaTitle" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="@Model.Locales[item].MetaTitle" />
                <span asp-validation-for="@Model.Locales[item].MetaTitle"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="@Model.Locales[item].SeName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="@Model.Locales[item].SeName" />
                <span asp-validation-for="@Model.Locales[item].SeName"></span>
            </div>
        </div>
        <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
    </div>;
}

<div class="form-horizontal">
    <localized-editor localized-template=@template name="course-seo-localized" language-ids=@Model.Locales.Select(c=>c.LanguageId).ToList()>
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="MetaKeywords" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="MetaKeywords" />
                    <span asp-validation-for="MetaKeywords"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="MetaDescription" />
                <div class="col-md-9 col-sm-9">
                    <admin-textarea asp-for="MetaDescription"></admin-textarea>
                    <span asp-validation-for="MetaDescription"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="MetaTitle" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="MetaTitle" />
                    <span asp-validation-for="MetaTitle"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="SeName" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="SeName" />
                    <span asp-validation-for="SeName"></span>
                </div>
            </div>
        </div>
    </localized-editor>
</div>

src/Web/Grand.Web.Admin/Areas/Admin/Views/Course/Partials/CreateOrUpdate.cshtml
@model CourseModel
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<input id="active-menu-item" type="hidden" value="/@Constants.AreaAdmin/Course/List" />
<admin-tabstrip name="category-edit">
    <items>
        <tabstrip-item text="@Loc["Admin.Courses.Course.Info"]" tab-index="0">
            <content>
                <div>
                    <partial name="Partials/CreateOrUpdate.TabInfo" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        <tabstrip-item text="@Loc["Admin.Common.SEO"]" tab-index="1">
            <content>
                <div>
                    <partial name="Partials/CreateOrUpdate.TabSeo" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        <tabstrip-item text="@Loc["Admin.Courses.Course.Subjects"]" tab-index="2">
            <content>
                <div>
                    <partial name="Partials/CreateOrUpdate.Subject" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        <tabstrip-item text="@Loc["Admin.Courses.Course.Lessons"]" tab-index="3">
            <content>
                <div>
                    <partial name="Partials/CreateOrUpdate.Lesson" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        <tabstrip-item text="@Loc["Admin.Common.UserFields.Tab"]" tab-index="4">
            <content>
                <div>
                    <partial name="Partials/UserFields" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        <vc:admin-widget widget-zone="course_details_tabs" additional-data="Model" />
    </items>
</admin-tabstrip>
<input id="active-menu-item" type="hidden" value="/@Constants.AreaAdmin/Course/List" />