src/Web/Grand.Web.Admin/Models/Discounts/DiscountListModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Grand.Web.Admin.Models.Discounts
{
    public partial class DiscountListModel : BaseModel
    {
        public DiscountListModel()
        {
            AvailableDiscountTypes = new List<SelectListItem>();
        }

        [GrandResourceDisplayName("admin.marketing.Discounts.List.SearchDiscountCouponCode")]
        
        public string SearchDiscountCouponCode { get; set; }

        [GrandResourceDisplayName("admin.marketing.Discounts.List.SearchDiscountName")]
        
        public string SearchDiscountName { get; set; }

        [GrandResourceDisplayName("admin.marketing.Discounts.List.SearchDiscountType")]
        public int SearchDiscountTypeId { get; set; }
        public IList<SelectListItem> AvailableDiscountTypes { get; set; }
    }
}

src/Web/Grand.Web.Admin/Controllers/DiscountController.cs
using Grand.Business.Core.Interfaces.Catalog.Brands;
using Grand.Business.Core.Interfaces.Catalog.Categories;
using Grand.Business.Core.Interfaces.Catalog.Collections;
using Grand.Business.Core.Interfaces.Catalog.Discounts;
using Grand.Business.Core.Interfaces.Catalog.Products;
using Grand.Business.Core.Interfaces.Common.Directory;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Common.Stores;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Business.Core.Interfaces.Customers;
using Grand.Domain;
using Grand.Infrastructure;
using Grand.Web.Admin.Extensions;
using Grand.Web.Admin.Interfaces;
using Grand.Web.Admin.Models.Catalog;
using Grand.Web.Admin.Models.Discounts;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Grand.Web.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.Discounts)]
    public partial class DiscountController : BaseAdminController
    {
        #region Fields

        private readonly IDiscountViewModelService _discountViewModelService;
        private readonly IDiscountService _discountService;
        private readonly ITranslationService _translationService;
        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly IDateTimeService _dateTimeService;
        private readonly IGroupService _groupService;

        #endregion

        #region Constructors

        public DiscountController(
            IDiscountViewModelService discountViewModelService,
            IDiscountService discountService,
            ITranslationService translationService,
            IWorkContext workContext,
            IStoreService storeService,
            IDateTimeService dateTimeService,
            IGroupService groupService)
        {
            _discountViewModelService = discountViewModelService;
            _discountService = discountService;
            _translationService = translationService;
            _workContext = workContext;
            _storeService = storeService;
            _dateTimeService = dateTimeService;
            _groupService = groupService;
        }

        #endregion

        #region Discounts

        //list
        public IActionResult Index() => RedirectToAction("List");

        public IActionResult List()
        {
            var model = _discountViewModelService.PrepareDiscountListModel();
            return View(model);
        }

        [HttpPost]
        [PermissionAuthorizeAction(PermissionActionName.List)]
        public async Task<IActionResult> List(DiscountListModel model, DataSourceRequest command)
        {
            var (discountModel, totalCount) = await _discountViewModelService.PrepareDiscountModel(model, command.Page, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = discountModel.ToList(),
                Total = totalCount
            };
            return Json(gridModel);
        }

        //create
        [PermissionAuthorizeAction(PermissionActionName.Create)]
        public async Task<IActionResult> Create()
        {
            var model = new DiscountModel();
            await _discountViewModelService.PrepareDiscountModel(model, null);

            //default values
            model.LimitationTimes = 1;
            return View(model);
        }

        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        [PermissionAuthorizeAction(PermissionActionName.Create)]
        public async Task<IActionResult> Create(DiscountModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                if (await _groupService.IsStaff(_workContext.CurrentCustomer))
                {
                    model.Stores = new string[] { _workContext.CurrentCustomer.StaffStoreId };
                }

                var discount = await _discountViewModelService.InsertDiscountModel(model);
                Success(_translationService.GetResource("admin.marketing.discounts.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = discount.Id }) : RedirectToAction("List");
            }
            //If we got this far, something failed, redisplay form
            await _discountViewModelService.PrepareDiscountModel(model, null);

            return View(model);
        }

        //edit
        [PermissionAuthorizeAction(PermissionActionName.Preview)]
        public async Task<IActionResult> Edit(string id)
        {
            var discount = await _discountService.GetDiscountById(id);
            if (discount == null)
                //No discount found with the specified id
                return RedirectToAction("List");

            if (await _groupService.IsStaff(_workContext.CurrentCustomer))
            {
                if (!discount.LimitedToStores || (discount.LimitedToStores && discount.Stores.Contains(_workContext.CurrentCustomer.StaffStoreId) && discount.Stores.Count > 1))
                    Warning(_translationService.GetResource("admin.marketing.discounts.Permisions"));
                else
                {
                    if (!discount.AccessToEntityByStore(_workContext.CurrentCustomer.StaffStoreId))
                        return RedirectToAction("List");
                }
            }

            var model = discount.ToModel(_dateTimeService);
            await _discountViewModelService.PrepareDiscountModel(model, discount);

            return View(model);
        }

        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        public async Task<IActionResult> Edit(DiscountModel model, bool continueEditing)
        {
            var discount = await _discountService.GetDiscountById(model.Id);
            if (discount == null)
                //No discount found with the specified id
                return RedirectToAction("List");

            if (await _groupService.IsStaff(_workContext.CurrentCustomer))
            {
                if (!discount.AccessToEntityByStore(_workContext.CurrentCustomer.StaffStoreId))
                    return RedirectToAction("Edit", new { id = discount.Id });
            }

            if (ModelState.IsValid)
            {
                if (await _groupService.IsStaff(_workContext.CurrentCustomer))
                {
                    model.Stores = new string[] { _workContext.CurrentCustomer.StaffStoreId };
                }
                discount = await _discountViewModelService.UpdateDiscountModel(discount, model);
                Success(_translationService.GetResource("admin.marketing.discounts.Updated"));
                if (continueEditing)
                {
                    //selected tab
                    await SaveSelectedTabIndex();
                    return RedirectToAction("Edit", new { id = discount.Id });
                }
                return RedirectToAction("List");
            }
            //If we got this far, something failed, redisplay form
            await _discountViewModelService.PrepareDiscountModel(model, discount);

            return View(model);
        }

        //delete
        [HttpPost]
        [PermissionAuthorizeAction(PermissionActionName.Delete)]
        public async Task<IActionResult> Delete(string id)
        {
            var discount = await _discountService.GetDiscountById(id);
            if (discount == null)
                //No discount found with the specified id
                return RedirectToAction("List");

            if (await _groupService.IsStaff(_workContext.CurrentCustomer))
            {
                if (!discount.AccessToEntityByStore(_workContext.CurrentCustomer.StaffStoreId))
                    return RedirectToAction("Edit", new { id = discount.Id });
            }

            var usagehistory = await _discountService.GetAllDiscountUsageHistory(discount.Id);
            if (usagehistory.Count > 0)
            {
                Error(_translationService.GetResource("admin.marketing.discounts.Deleted.UsageHistory"));
                return RedirectToAction("Edit", new { id = discount.Id });
            }
            if (ModelState.IsValid)
            {
                await _discountViewModelService.DeleteDiscount(discount);
                Success(_translationService.GetResource("admin.marketing.discounts.Deleted"));
                return RedirectToAction("List");
            }
            Error(ModelState);
            return RedirectToAction("Edit", new { id = discount.Id });
        }

        #endregion

        #region Discount coupon codes
        [HttpPost]
        [PermissionAuthorizeAction(PermissionActionName.Preview)]
        public async Task<IActionResult> CouponCodeList(DataSourceRequest command, string discountId)
        {
            var discount = await _discountService.GetDiscountById(discountId);
            if (discount == null)
                throw new Exception("No discount found with the specified id");

            var couponcodes = await _discountService.GetAllCouponCodesByDiscountId(discount.Id, pageIndex: command.Page - 1, pageSize: command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = couponcodes.Select(x => new
                {
                    Id = x.Id,
                    CouponCode = x.CouponCode,
                    Used = x.Used
                }),
                Total = couponcodes.TotalCount
            };
            return Json(gridModel);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        public async Task<IActionResult> CouponCodeDelete(string discountId, string Id)
        {
            var discount = await _discountService.GetDiscountById(discountId);

src/Web/Grand.Web.Admin/Areas/Admin/Views/Discount/BrandAddPopup.cshtml
@model DiscountModel.AddBrandToDiscountModel
@inject AdminAreaSettings adminAreaSettings
@{
    Layout = "";
    //page title
    ViewBag.Title = Loc["admin.marketing.Discounts.AppliedToBrands.AddNew"];
}

<form id="BrandAddPopup" asp-area="@Constants.AreaAdmin" asp-controller="Discount" asp-action="BrandAddPopup" method="post"
      asp-route-DiscountId="@Context.Request.Query["DiscountId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">

    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-cubes"></i>
                        @Loc["admin.marketing.Discounts.AppliedToBrands.AddNew"]
                    </div>
                </div>
                <div class="x_content form">
                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="main-header col-12 px-0 mb-3">
                                <div class="row align-items-end">
                                    <div class="col-md-8 col-sm-12 col-12">
                                        <div class="form-group mb-0">
                                            <admin-label asp-for="SearchBrandName" class="control-label" />
                                            <admin-input asp-for="SearchBrandName" />
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12 col-12">
                                        <div class="form-actions">
                                            <div class="btn-group btn-group-devided">
                                                <button class="btn btn-success filter-submit" id="search-brands"><i class="fa fa-search"></i> @Loc["Admin.Common.Search"]</button>
                                                <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="brands-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
            var mfp = $.magnificPopup.instance;
            $("#BrandAddPopup").submit(function (e) {
                e.preventDefault();
                var form = $(this);
                var url = form.attr('action');
                $.ajax({
                    type: "POST",
                    url: url,
                    data: form.serialize(),
                    success: function (data) {
                        if (data == "") {
                            mfp.close();
                            $('#btnRefreshBrands').click();
                        } else {
                            $.magnificPopup.open({
                                items: {
                                    src: data,
                                    type: 'inline'
                                },
                                callbacks: {
                                    open: function () {
                                        $('.mfp-wrap').removeAttr('tabindex');
                                    }
                                }
                            });
                        }
                    }
                });
            });
            $("#brands-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("BrandAddPopupList", "Discount", new { area = Constants.AreaAdmin }))",
                            type: "POST",
                            dataType: "json",
                            data: additionalData
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "Id",
                    headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                    headerAttributes: { style: "text-align:center" },
                    template: "<input type='checkbox' name='SelectedBrandIds' value='#=Id#' class='checkboxGroups' />",
                    attributes: { style: "text-align:center" },
                    width: 50
                }, {
                    field: "Name",
                    title: "@Loc["Admin.Catalog.Brands.Fields.Name"]"
                }
                ]
            });

            $('#search-brands').click(function() {
                var grid = $('#brands-grid').data('kendoGrid');
                grid.dataSource.page(1); //new search. Set page size to 1
                //grid.dataSource.read(); we already loaded the grid above using "page" function
                //clear selected checkboxes
                $('.checkboxGroups').prop('checked', false).change();
                return false;
            });

            $("#@Html.IdFor(model => model.SearchBrandName)").keydown(function(event) {
                if (event.keyCode == 13) {
                    $("#search-vendors").click();
                    return false;
                }
            });

            //wire up checkboxes
            $('#mastercheckbox').click(function() {
                $('.checkboxGroups').prop('checked', $(this).is(':checked')).change();
            });

            $('#brands-grid').on('change', 'input[type=checkbox][id!=mastercheckbox]', function(e) {
                updateMasterCheckbox();
            });

        function additionalData() {
            var data = {
                SearchBrandName: $('#@Html.IdFor(model => model.SearchBrandName)').val(),
            };
            addAntiForgeryToken(data);
            return data;
        }

        function updateMasterCheckbox() {
            var numChkBoxes = $('#brands-grid input[type=checkbox][id!=mastercheckbox]').length;
            var numChkBoxesChecked = $('#brands-grid input[type=checkbox][id!=mastercheckbox]:checked').length;
            $('#mastercheckbox').prop('checked', numChkBoxes == numChkBoxesChecked && numChkBoxes > 0);
        }

    </script>

</form>

src/Web/Grand.Web.Admin/Areas/Admin/Views/Discount/CategoryAddPopup.cshtml
@model DiscountModel.AddCategoryToDiscountModel
@inject AdminAreaSettings adminAreaSettings
@{
    Layout = "";
    //page title
    ViewBag.Title = Loc["admin.marketing.Discounts.AppliedToCategories.AddNew"];
}

<form id="CategoryAddPopup" asp-area="@Constants.AreaAdmin" asp-controller="Discount" asp-action="CategoryAddPopup" method="post"
      asp-route-DiscountId="@Context.Request.Query["DiscountId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">   

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-cubes"></i>
                        @Loc["admin.marketing.Discounts.AppliedToCategories.AddNew"]
                    </div>
                </div>
                <div class="x_content form">
                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="main-header col-12 px-0 mb-3">
                                <div class="row align-items-end">
                                    <div class="col-md-8 col-sm-12 col-12">
                                        <div class="form-group mb-0">
                                            <admin-label asp-for="SearchCategoryName" class="control-label" />
                                            <admin-input asp-for="SearchCategoryName" />
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-12 col-12">
                                        <div class="form-actions">
                                            <div class="btn-group btn-group-devided">
                                                <button class="btn btn-success filter-submit" id="search-categories"><i class="fa fa-search"></i> @Loc["Admin.Common.Search"]</button>
                                                <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="categories-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var mfp = $.magnificPopup.instance;
        $("#CategoryAddPopup").submit(function (e) {
                e.preventDefault();
                var form = $(this);
                var url = form.attr('action');
                $.ajax({
                    type: "POST",
                    url: url,
                    data: form.serialize(),
                    success: function (data) {
                        if (data == "") {
                            mfp.close();
                            $('#btnRefreshCategories').click();
                        } else {
                            $.magnificPopup.open({
                                items: {
                                    src: data,
                                    type: 'inline'
                                },
                                callbacks: {
                                    open: function () {
                                        $('.mfp-wrap').removeAttr('tabindex');
                                    }
                                }
                            });
                        }
                    }
                });
        });
        $("#categories-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("CategoryAddPopupList", "Discount", new { area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: additionalData
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors"
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: @(adminAreaSettings.DefaultGridPageSize),
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                pageSizes: [@(adminAreaSettings.GridPageSizes)]
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "Id",
                headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                headerAttributes: { style: "text-align:center" },
                template: "<input type='checkbox' name='SelectedCategoryIds' value='#=Id#' class='checkboxGroups' />",
                attributes: { style: "text-align:center" },
                width: 50
            }, {
                field: "Breadcrumb",
                title: "@Loc["Admin.Catalog.Categories.Fields.Name"]"
            }, {
                field: "Published",
                title: "@Loc["Admin.Catalog.Categories.Fields.Published"]",
                width: 100,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(Published) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            }]
        });

                        $('#search-categories').click(function() {
                            var grid = $('#categories-grid').data('kendoGrid');
                            grid.dataSource.page(1); //new search. Set page size to 1
                            //grid.dataSource.read(); we already loaded the grid above using "page" function
                            //clear selected checkboxes
                            $('.checkboxGroups').prop('checked', false).change();
                            return false;
                        });

                        $("#@Html.IdFor(model => model.SearchCategoryName)").keydown(function(event) {
                            if (event.keyCode == 13) {
                                $("#search-categories").click();
                                return false;
                            }
                        });

                        //wire up checkboxes
                        $('#mastercheckbox').click(function() {
                            $('.checkboxGroups').prop('checked', $(this).is(':checked')).change();
                        });

                        $('#categories-grid').on('change', 'input[type=checkbox][id!=mastercheckbox]', function(e) {
                            updateMasterCheckbox();
                        });

                    function additionalData() {
                        var data = {
                            SearchCategoryName: $('#@Html.IdFor(model => model.SearchCategoryName)').val()
                        };
                        addAntiForgeryToken(data);
                        return data;
                    }

                    function updateMasterCheckbox() {
                        var numChkBoxes = $('#categories-grid input[type=checkbox][id!=mastercheckbox]').length;
                        var numChkBoxesChecked = $('#categories-grid input[type=checkbox][id!=mastercheckbox]:checked').length;
                        $('#mastercheckbox').prop('checked', numChkBoxes == numChkBoxesChecked && numChkBoxes > 0);
                    }

    </script>
</form>

src/Web/Grand.Web.Admin/Areas/Admin/Views/Discount/Create.cshtml
@model DiscountModel
@{
    //page title
    ViewBag.Title = Loc["admin.marketing.Discounts.AddNew"];
}
<form asp-area="@Constants.AreaAdmin" asp-controller="Discount" asp-action="Create" method="post" id="discount-form">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-tags"></i>
                        @Loc["admin.marketing.Discounts.AddNew"]
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["admin.marketing.Discounts.BackToList"], "List")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>
                            <vc:admin-widget widget-zone="discount_details_buttons" additional-data="null" />
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="Partials/CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

src/Web/Grand.Web.Admin/Areas/Admin/Views/Discount/Edit.cshtml
@model DiscountModel
@{
    //page title
    ViewBag.Title = Loc["admin.marketing.Discounts.EditDiscountDetails"];
}
<form asp-area="@Constants.AreaAdmin" asp-controller="Discount" asp-action="Edit" method="post" id="discount-form">
    
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-tags"></i>
                        @Loc["admin.marketing.Discounts.EditDiscountDetails"] - @Model.Name
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["admin.marketing.Discounts.BackToList"], "List")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>
                            <span id="discount-delete" class="btn red"><i class="fa fa-trash-o"></i> @Loc["Admin.Common.Delete"]</span>
                            <vc:admin-widget widget-zone="discount_details_buttons" additional-data="Model" />
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="Partials/CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>
<admin-delete-confirmation button-id="discount-delete"/>